from environs import Env

env = Env()
env.read_env()

RANDOM_SEED = env.int("RANDOM_SEED")
SIM_TIME = env.int("SIM_TIME")

# config for simulate bank
NUM_OF_BANK_TELLERS = env.int("NUM_OF_BANK_TELLERS")
AVG_SERVICE_TIME = env.float("AVG_SERVICE_TIME")
CUSTOMER_INTERVAL = env.float("CUSTOMER_INTERVAL")

# config for simulate hospital
PATIENT_TYPES = env.list("PATIENT_TYPES")
PATIENT_INTERVAL_TIMES = env.json("PATIENT_INTERVAL_TIMES")
AVG_REGISTRATION_TIMES = env.json("AVG_REGISTRATION_TIMES")

RECEPTION_TRIP_TIME = env.float("RECEPTION_TRIP_TIME")

CHAMBER_TRIP_TIME_LOW = env.float("CHAMBER_TRIP_TIME_LOW")
CHAMBER_TRIP_TIME_HIGH = env.float("CHAMBER_TRIP_TIME_HIGH")

LAB_TRIP_TIME_LOW = env.float("LAB_TRIP_TIME_LOW")
LAB_TRIP_TIME_HIGH = env.float("LAB_TRIP_TIME_HIGH")

LAB_REGISTRY_TIME_SHAPE = env.float("LAB_REGISTRY_TIME_SHAPE")
LAB_REGISTRY_TIME_SCALE = env.float("LAB_REGISTRY_TIME_SCALE")

LAB_ANALYSIS_TIME_SHAPE = env.float("LAB_ANALYSIS_TIME_SHAPE")
LAB_ANALYSIS_TIME_SCALE = env.float("LAB_ANALYSIS_TIME_SCALE")
